export interface Branch { id: number; name: string; address?: string; phone?: string; open_time: string; close_time: string; active: boolean; }
export interface Service { id: number; name: string; category: string; price: number; duration: number; description?: string; active: boolean; }
export interface Staff { id: number; name: string; role: string; branch_id: number | null; phone?: string; email?: string; specialties?: string; rating: number; photo?: string; commission_rate: number; base_salary: number; active: boolean; }
export interface Customer { id: number; name: string; phone: string; email?: string; gender?: string; birthday?: string; address?: string; tags?: string; notes?: string; loyalty_points: number; total_visits: number; total_spent: number; last_visit?: string; created_at?: string; }
export interface Appointment { id: number; booking_ref: string; customer_id: number | null; customer_name: string; customer_phone: string; branch_id: number | null; branch_name?: string; staff_id: number | null; staff_name?: string; service_id: number | null; service_name?: string; items?: any[]; date: string; time: string; duration: number; total_price: number; status: string; payment_status: string; notes?: string; created_at?: string; }
export interface Transaction { id: number; invoice_no: string; branch_id: number | null; branch_name?: string; staff_id: number | null; staff_name?: string; customer_id: number | null; customer_name?: string; appointment_id: number | null; items: any[]; subtotal: number; discount: number; tax: number; total: number; payment_method: string; amount_tendered: number; change_due: number; status: string; cashier?: string; created_at?: string; }
export interface Product { id: number; name: string; sku?: string; category?: string; brand?: string; price: number; cost: number; stock: number; reorder_level: number; branch_id: number | null; supplier_id: number | null; active: boolean; }
export interface Supplier { id: number; name: string; contact_person?: string; phone?: string; email?: string; address?: string; active: boolean; }
export interface PurchaseOrder { id: number; po_no: string; supplier_id: number | null; supplier_name?: string; branch_id: number | null; branch_name?: string; items: any[]; total: number; status: string; expected_date?: string; notes?: string; created_by?: string; created_at?: string; }
export interface Expense { id: number; date: string; category: string; description: string; amount: number; branch_id: number | null; branch_name?: string; payment_method?: string; receipt_no?: string; created_by?: string; }
export interface PayrollRow { id: number; month: string; staff_id: number | null; staff_name?: string; branch_name?: string; base_salary: number; commission: number; deductions: number; net_pay: number; status: string; paid_at?: string; }
export interface UserRow { id: number; name: string; email: string; role: string; branch_id: number | null; branch_name?: string; active: boolean; }
export interface SettingRow { id: number; key: string; value: string; }
